apiVersion: apps/v1
kind: Deployment
metadata:
  name: ltdevents
  labels:
    app: ltdevents
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ltdevents
  template:
    metadata:
      labels:
        name: ltdevents
    spec:
      containers:
        - name: app
          imagePullPolicy: "Always"
          # Use images field in a Kustomization to regularly set/update image tag
          image: "lsstsqre/ltdevents"
          ports:
            - containerPort: 8080
              name: app
          envFrom:
            - configMapRef:
                name: ltdevents
