apiVersion: v1
kind: Service
metadata:
  name: ltdevents
  labels:
    app: ltdevents
spec:
  ports:
    - name: ltdevents-http
      protocol: TCP
      port: 8080
      targetPort: app
  selector:
    name: ltdevents
